<section class="bg-100">

    <div class="container">
        <div class="text-center mb-6 mt-3">
            <h3 class="fs-2 fs-md-3"><?= $title; ?></h3>
            <hr class="short" data-zanim-xs='{"from":{"opacity":0,"width":0},"to":{"opacity":1,"width":"4.20873rem"},"duration":0.8}' data-zanim-trigger="scroll" />
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card mb-6">
                    <div class="card-body p-5">
                        <h4>Mahbub Djunaidi</h4>
                        <p><b>Mahbub Djunaidi</b> adalah ketua umum pertama Pergerakan Mahasiswa Islam Indonesia (PMII). Ia lahir di Jakarta pada 22 Juli 1933. Ia dikenal sebagai wartawan-sastrawan, agamawan, organisatoris, kolumnis, politikus, serta predikat baik lainnya yang disemangatkan di pundaknya. Ini bukan predikat main-main, karena ia memang seorang yang memiliki talenta luar biasa. Kritik-kritik sosial dalam tulisannya begitu tajam, begitu dalam. Tentu saja dengan ciri khas yang dimilikinya: satire dan humoris. Karena kepiawaiannya dalam menulis, ia disebut pendekar pena, bahkan Bung Karno terkesan dengannya.  Kebiasaan menulis telah ia lakukan sejak duduk di bangku SMP. Bahkan di masa itu, cerpennya berjudul Tanah Mati dipublikasikan oleh Kisah, sebuah majalah kumpulan cerita pendek bermutu, disertai komentar dan penilaian pengelolanya HB Jassin, sang legendaris paus sastra Indonesia itu. HB Jassin sangat kagum dengan tulisan Mahbub muda. Baginya, Mahbub mampu memandang persoalan dari seginya yang kocak. Elaborasi antara humor dan satire (cemooh kocak) disertai dengan unsur kritik. Gaya tulisannya ringan dan menyenangkan, seolah-olah main-main, tetapi persoalan serius yang diangkat.  Keberaniannya menyuarakan kebenaran dan membela wong cilik tak perlu diragukan. Sampai-sampai ia dijuluki si burung parkit di kandang macan. Ia banyak menulis, memberi perhatian dan pembelaan kepada kaum miskin. Termasuk kepada anak-anak pedagang asongan dan para pengemis cilik di persimpangan-persimpangan jalan. Ia dikenal sebagai pribadi yang ringan ceria, kocak berolok. Baginya semua orang tak ada bedanya, tidak bermartabat lebih tinggi dan lebih rendah, hanya karena jabatan dan pekerjaannya. Lapisan pergaulannya sangat luas, dan semua disapa dengan Anda, dengan saudara, dengan bung.</p>
                        <p>Di dunia sastra, Mahbub sangat menyenangi sastra Rusia karena dalam penilaiannya, sastrawan Rusia banyak melahirkan karya sastra yang sarat dengan kritik tajam dan dituturkan secara satire. Humor-humor kecil menjadikan kritik-kritik tersebut terkesan lucu. Pandangan dan kesukaannya inilah yang banyak memengaruhinya untuk memproduksi tulisan yang mengandung humor tinggi. Tak heran jika sebagian besar kolom Mahbub berisi masalah-masalah politik dan sosial tetapi penyajiannya bernilai sastra.  Tulisan-tulisannya yang sarat humor ini membuat siapapun yang terkena tidak merasa sakit hati, malahan menimbulkan guncangan yang tak perlu. Tak bisa dimungkiri, unsur kejenakaan dalam tulisannya membuat pembaca tertawa dalam keadaan serius. Apalagi ia mampu menyajikan efek haru yang syarat emosional. Menghibur dan menggugat, melecut tawa dan menorehkan kepedihan, itulah humor pada kadar tertingginya. Mahbub berhasil memunculkan paradoks humor itu. Mahbub pernah memimpin sejumlah media masa, juga menulis dan menerjemahkan puluhan buku. Ia juga dikenal sebagai wartawan yang gigih dan bekerja keras dan konsisten untuk sejauh mungkin memelihara kewartawanan serta organisasi wartawan sebagai profesi dan organisasi yang mandiri. Sejak menjadi wartawan, ia memiliki rutinitas setiap hari menyelesaikan tulisan tajuk rencana koran dalam waktu relatif cepat, sekitar 1-2 jam. Kadang dibuatnya satu, kadang dua buah sekaligus. Itu dilakukannya sendiri, bertahun-tahun.</p>  
                        <p>Bahkan, sejak 23 November 1986 sampai 8 Oktober 1995, ia menulis rutin setiap minggu untuk rubrik Asal Usul di koran harian Kompas. Rubrik ini mensyaratkan tulisan yang amat ketat. Tulisan-tulisannya di rubrik ini disinggung dan dipaparkan secara ringan dan lebih menekankan pada sisi humornya. Rintangan tulisan yang penuh syarat ini mampu dipenuhi Mahbub. Selama 9 tahun menulis di rubrik ini, ia telah menulis 236 buah tulisan. Kenapa Mahbub bisa memenuhi syarat tulisan yang relatif sulit ini? karena dalam dirinya sudah ada tiga ciri menonjol: politikus, wartawan dan humoris.  Dalam salah satu tulisannya di harian Duta Masyarakat, Mahbub mengemukakan pendapatnya bahwa Pancasila mempunyai kedudukan lebih sublim dibanding Declaration of Independence susunan Thomas Jefferson yang menjadi pernyataan kemerdekaan Amerika Serikat tanggal 4 Juli 1776, maupun dengan Manifesto Komunis yang disusun oleh Karl Marx dan Friedrich Engels tahun 1847. Tulisan itu dibaca Bung Karno, dan karena tulisan itu Bung Karno takjub kepadanya dan tulisan-tulisannya. Di luar kegiatan tulis menulis, Mahbub pernah bergabung dengan Ikatan Pelajar Nahdlatul Ulama (IPNU) selagi masih duduk di SMA. Pada tahun 1960, ia terpilih menjadi ketua umum PMII. Selama menjadi ketua umum PMII, Mahbub berusaha dengan sungguh-sungguh menjadikan PMII wadah pembentukan kader, sebagaimana diamanatkan kepadanya oleh Musyawarah NU seluruh Indonesia. Salah satu cara membentuk jiwa dan menempa semangat kader adalah melalui lagu-lagu, khususnya lagu mars organisasi. Dia sendiri menyusun lirik lagu mars PMII, lagu yang dinyanyikan pada setiap kesempatan dan pada saat akan memulai acar penting PMII, hingga sekarang.</p>
                        <p>Source: NU Online</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>